server:
  port: 8761

spring:
  application:
    name: discovery-server

# Disable Spring Cloud Config
  cloud:
    config:
      enabled: false

# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 5000
    peer-eureka-nodes-update-interval-ms: 10000

# Logging Configuration
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: discovery-server