server:
  port: 8088

# Spring configuration
spring:
  application:
    name: gateway
  # Allow bean definition overriding to resolve conflicts between Resilience4j versions
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/userServiceFallback
                statusCodes: 500, 502, 503, 504, 404
            - name: RewritePath
              args:
                regexp: /api/(?<segment>.*)
                replacement: /${segment}
# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true


# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
    instances:
      userServiceCB:
        baseConfig: default
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  
  # Enable metrics for monitoring
  metrics:
    enable: true
    distribution:
      percentiles: [0.5, 0.9, 0.95, 0.99]
  
  # Enable health indicators
  health:
    circuitbreaker:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.commons: DEBUG
    com.example.gateway: DEBUG
